### ISSUE TITLE
Exporting an image

### ISSUE THREAD

**Issue by mapmeld** [jywarren/webgl-distort#5]
Since dataURL wouldn't work for rendering the final image, I'm wondering if you could have the user do the warping and distortion, save those matrices so that the editing can be repeated, and send it to a server to make the PNG.  Using NodeJS you could use the same matrices and same code behind image editing.  I've used node-canvas a lot for image effects, but I haven't tried node-webgl yet.

**Comment by jywarren** [comment]
Well, this is sort of riffing on the server-side export system for
MapKnitter.org, which already does imagemagick-based server-side
transforms. The goal is to do the export client-side, in pure
JavaScript/webgl.

Why won't dataURL work for rendering the final image? It seems to be
working now in the demo, does it not work for you?
